"use client";

import * as React from "react";
import {
  Document,
  Page,
  PDFDownloadLink,
  StyleSheet,
  Text,
  View,
} from "@react-pdf/renderer";
import { Download } from "lucide-react";
import { cn } from "@/lib/utils";

export interface ReceiptData {
  gymName: string;
  number: string;
  memberName: string;
  issuedOn: string;
  items: { description: string; quantity: number; amountPaise: number }[];
  subtotalPaise: number;
  discountPaise: number;
  taxPaise: number;
  totalPaise: number;
  paidPaise: number;
  duePaise: number;
}

const rupees = (p: number) => "INR " + (p / 100).toLocaleString("en-IN");

const s = StyleSheet.create({
  page: { padding: 36, fontSize: 10, color: "#17191c", fontFamily: "Helvetica" },
  h1: { fontSize: 18, fontFamily: "Helvetica-Bold" },
  muted: { color: "#6b6f68" },
  row: { flexDirection: "row", justifyContent: "space-between", marginBottom: 3 },
  hr: { borderBottomWidth: 1, borderBottomColor: "#e6e6df", marginVertical: 10 },
  th: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "#17191c", paddingBottom: 4, marginBottom: 4, fontFamily: "Helvetica-Bold" },
  cellDesc: { flex: 1 },
  cellQty: { width: 40, textAlign: "right" },
  cellAmt: { width: 80, textAlign: "right" },
  totals: { marginTop: 10, marginLeft: "auto", width: 200 },
  footer: { position: "absolute", bottom: 30, left: 36, right: 36, fontSize: 8, color: "#6b6f68" },
});

function ReceiptDoc({ data }: { data: ReceiptData }) {
  return (
    <Document>
      <Page size="A4" style={s.page}>
        <View style={s.row}>
          <Text style={s.h1}>{data.gymName}</Text>
          <View>
            <Text style={{ fontFamily: "Helvetica-Bold" }}>RECEIPT</Text>
            <Text style={s.muted}>{data.number}</Text>
          </View>
        </View>
        <View style={s.hr} />
        <View style={s.row}>
          <Text>Billed to: {data.memberName}</Text>
          <Text style={s.muted}>Date: {data.issuedOn}</Text>
        </View>

        <View style={{ marginTop: 16 }}>
          <View style={s.th}>
            <Text style={s.cellDesc}>Description</Text>
            <Text style={s.cellQty}>Qty</Text>
            <Text style={s.cellAmt}>Amount</Text>
          </View>
          {data.items.map((it, i) => (
            <View key={i} style={{ flexDirection: "row", marginBottom: 3 }}>
              <Text style={s.cellDesc}>{it.description}</Text>
              <Text style={s.cellQty}>{it.quantity}</Text>
              <Text style={s.cellAmt}>{rupees(it.amountPaise)}</Text>
            </View>
          ))}
        </View>

        <View style={s.totals}>
          <View style={s.row}><Text style={s.muted}>Subtotal</Text><Text>{rupees(data.subtotalPaise)}</Text></View>
          {data.discountPaise > 0 && <View style={s.row}><Text style={s.muted}>Discount</Text><Text>- {rupees(data.discountPaise)}</Text></View>}
          {data.taxPaise > 0 && <View style={s.row}><Text style={s.muted}>Tax</Text><Text>{rupees(data.taxPaise)}</Text></View>}
          <View style={[s.row, { fontFamily: "Helvetica-Bold" }]}><Text>Total</Text><Text>{rupees(data.totalPaise)}</Text></View>
          <View style={s.row}><Text style={s.muted}>Paid</Text><Text>{rupees(data.paidPaise)}</Text></View>
          <View style={[s.row, { fontFamily: "Helvetica-Bold" }]}><Text>Due</Text><Text>{rupees(data.duePaise)}</Text></View>
        </View>

        <Text style={s.footer}>
          Terms &amp; conditions: Fees once paid are non-refundable. This is a computer-generated receipt and needs no signature. Generated by {data.gymName} on GymHere.
        </Text>
      </Page>
    </Document>
  );
}

export function ReceiptDownload({ data, className }: { data: ReceiptData; className?: string }) {
  const [mounted, setMounted] = React.useState(false);
  React.useEffect(() => setMounted(true), []);

  const cls = cn(
    "inline-flex h-9 items-center justify-center gap-2 rounded-md bg-primary px-4 text-sm font-semibold text-primary-foreground transition-colors hover:bg-primary/90",
    className,
  );

  if (!mounted) {
    return <span className={cn(cls, "pointer-events-none opacity-60")}><Download className="size-4" /> Download PDF</span>;
  }

  return (
    <PDFDownloadLink document={<ReceiptDoc data={data} />} fileName={`${data.number}.pdf`} className={cls}>
      {({ loading }) => (<><Download className="size-4" /> {loading ? "Preparing…" : "Download PDF"}</>)}
    </PDFDownloadLink>
  );
}
